spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task_management_db
    username: name
    password: password
    hikari:
      driver-class-name: org.postgresql.Driver
      schema: task_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS task_schema
      connection-timeout: 10000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

